---

- name: Ensure git
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - acl
    - rsync

- name: Ensure golang
  apt:
    name: golang
    default_release: "{{ ansible_distribution_release }}"

- name: Create yanic user
  user:
    name: "{{ yanic_user }}"
    group: "{{ yanic_group }}"
    system: yes

- name: Install yanic
  become: true
  become_user: "{{ yanic_user }}"
  script: /usr/bin/go install {{ yanic_repo_path }}@{{ yanic_tag }}

- name: Ensure persist directory, if needed
  file:
    path: "/var/lib/yanic/"
    state: directory
    owner: yanic
  when: yanic_nodes_enabled

- name: Ensure nodes path, if needed
  file:
    path: "{{ yanic_nodes_path }}"
    state: directory
    owner: yanic
    group: www-data
  when: yanic_nodes_enabled

- name: Configure yanic (DIFF REDACTED)
  notify: Restart yanic
  template:
    src: yanic.conf.j2
    dest: /etc/yanic.conf

- name: Copy systemd service
  notify: Daemon reload
  template:
    src: yanic.service.j2
    dest: /lib/systemd/system/yanic.service

- name: Enable yanic
  systemd:
    name: yanic
    state: restarted
    enabled: yes
    daemon_reload: yes