# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: 'yanic-influxdb'
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: ff
  type: influxdb
  url: "localhost{{ influx2_bind_address }}"
  user: ff
  database: freifunk
  secureJsonData:
    password: ff
  isDefault: true
  editable: true