---

- name: Add repo key
  apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present

- name: Add influx repo
  register: influxrepositoryadded
  apt_repository:
    repo: "deb https://repos.influxdata.com/debian stable main"

- name: Update apt chache to get influxdb packages
  apt: update_cache=yes
  when: influxrepositoryadded is changed

- name: Install influxdb from repo
  register: influxinstall
  apt:
    name: influxdb
    state: latest

- name: Ensure engine directory exists and has correct ownership
  file:
    state: directory
    path: "{{ influx_engine_path }}"
    owner: "influxdb"
    group: "influxdb"
    recurse: yes

# - name: Generate firewall config stanza (ferm)
#   register: ferm_changed
#   template:
#     src: ferm.conf.j2
#     dest: /etc/ferm/conf.d/50-influxdb.conf
#   notify: reload ferm

- name: Restart influxdb2 service
  systemd:
    name: influxdb
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Create ffac user - no auth on first install
  community.general.influxdb_user:
    login_username: "{{ influxdb_username }}"
    login_password: "{{ influxdb_password }}"
    user_name: "{{ influxdb_username }}"
    user_password: "{{ influxdb_password }}"
    admin: true

- name: Generate config file - activate auth
  register: influx_configfile
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf


- name: Restart influxdb2 service - apply auth
  systemd:
    name: influxdb
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: influx_configfile is changed


- name: Create database using custom credentials
  community.general.influxdb_database:
      username: "{{influxdb_username}}"
      password: "{{influxdb_password}}"
      database_name: "{{influxdb_database_name}}"
      ssl: true
      validate_certs: true
