---

- name: Include 'Build from source'
  include_tasks: build_from_source.yml
  when: batman_build_from_source

- name: Install batctl
  apt: name=batctl
  when: not batman_build_from_source

- name: Install autostart batman_adv on boot
  lineinfile: dest=/etc/modules line=batman-adv

- name: Load batman_adv module
  modprobe: name=batman_adv state=present