---

- name: Install python3, git
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ packages }}"
  vars:
    packages:
    - python3
    - python3-pip
    - python3-requests
    - git

- name: Create auto user
  register: createuser
  user:
    name: auto
    system: yes
    generate_ssh_key: yes

- name: Create the peers directory
  file:
    state: directory
    dest: /etc/wireguard/peers-wg
    owner: auto

- name: Clone the peers git
  become: true
  become_user: auto
  git:
    repo: "{{ git_addr }}/peers-wg"
    dest: /etc/wireguard/peers-wg
    accept_hostkey: true
    version: main

- name: Clone segmenter-watchdog
  become: true
  become_user: auto
  git:
    repo: https://github.com/ffac/autosegmenter
    dest: /home/auto/autosegmenter
  register: updatewatchdog

- name: Set Git Config Mail
  become: true
  become_user: auto
  git_config:
    name: user.email
    repo: /etc/wireguard/peers-wg
    scope: local
    value: 'auto@{{ dns_searchdomains }}'

- name: Set Git Config User
  become: true
  become_user: auto
  git_config:
    name: user.name
    repo: /etc/wireguard/peers-wg
    scope: local
    value: 'auto'

- name: Install watchdog_config.json
  template:
    src: watchdog_config.json.j2
    dest: /home/auto/autosegmenter/watchdog_config.json
    owner: auto
    group: auto

- name: Install watchdog service
  template:
    src: ff-batman-watchdog.service.j2
    dest: /etc/systemd/system/ff-batman-watchdog.service
  register: servicefile

- name: Enable watchdog service
  systemd:
    name: ff-batman-watchdog.service
    state: started
    daemon_reload: yes
    enabled: yes
  when: servicefile is changed or updatewatchdog is changed