---

- name: "Create permissions folder"
  file:
    path: /etc/wireguard
    state: directory
    mode: "0650" 
    owner: "root"
    group: "systemd-network"    

- name: "Create wireguard privatekey file (dom {{ domain.id }}) (DIFF REDACTED)"
  copy:
    content: "{{ wireguard_keys['%02d' % sn][domain.id].secret }}" 
    dest: /etc/wireguard/privatekey-{{ '%02d' % domain.id | int }}
    mode: "0640" 
    owner: "root"
    group: "systemd-network"

- name: "Generate networkd wg netdev (dom {{ domain.id }}) (DIFF REDACTED)"
  template:
    src: wireguard.netdev.j2
    dest: "/etc/systemd/network/30-{{ mesh_wireguard_iface_prefix }}-{{ domain.id }}.netdev"
    mode: "0644"
    owner: "root"
    group: "systemd-network"
  #diff: "{{ show_secret_diffs }}"

- name: "Generate networkd wg network (dom {{ domain.id }})"
  template:
    src: wireguard.conf.j2
    dest: "/etc/systemd/network/30-{{ mesh_wireguard_iface_prefix }}-{{ domain.id }}.network"

- name: "Generate networkd vxlan netdev (dom {{ domain.id }})"
  template:
    src: vxlan.netdev.j2
    dest: "/etc/systemd/network/30-{{ vxlan_iface_prefix }}-{{ domain.id }}.netdev"

- name: "Generate networkd vxlan-server netdev (dom {{ domain.id }})"
  template:
    src: vxlan-server.netdev.j2
    dest: "/etc/systemd/network/30-{{ vxlan_iface_prefix }}-{{ domain.id }}-server.netdev"

- name: "Generate networkd bat device (dom {{ domain.id }})"
  template:
    src: network.j2
    dest: "/etc/systemd/network/10-bat{{ domain.id }}.network"
  notify: Restart networkd
