---
servername: sn01
sn: 01

# cloud-init config
networkd_interfaces:
  - name: eth0
    fixed_mac: 5a:d3:2c:f9:92:15
    addresses:
      - 5.145.135.151/27
      - 2a00:fe0:43::201/64
    gateway4: 5.145.135.129
    gateway6: 2a00:fe0:43::1
    dns_server:
      - 9.9.9.9
      - '2a03:2260:3006::53'
    nat4: True
    nat6: False
    additional_config: |
      [RoutingPolicyRule]
      From=2a03:2260:3006:100::/56
      Table=42

      [RoutingPolicyRule]
      From=2a03:2260:3006:200::/56
      Table=42

      [Route]
      Destination=::/0
      #Gateway=2a00:fe0:43::bb:2
      MultiPathRoute=2a00:fe0:43::bb:1
      MultiPathRoute=2a00:fe0:43::bb:2
      Table=42

client_dns_server_v4: 9.9.9.9
client_dns_server_v6: 2a03:2260:3006::53

# ffrl prefix
mesh_prefix: "2a03:2260:3006"
radv_announce_default: true

local_vxlan_supernode: 2a00:fe0:43::201
remote_vxlan_supernode: 2a00:fe0:43::202
yanic_central: "true"
