---

- name: Install python3, python3-psutil, lsb-release, ethtool, git
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ packages }}"
  vars:
    packages:
    - python3
    - python3-psutil
    - lsb-release
    - ethtool
    - git

- name: Create auto user
  register: createuser
  user:
    name: auto
    system: yes
    generate_ssh_key: yes

- name: Create mesh_announce directory
  file:
    state: directory
    dest: /opt/mesh-announce
    owner: auto

# repo=https://github.com/ffnord/mesh-announce.git
# change back when https://github.com/ffnord/mesh-announce/pull/84 got merged
- name: Clone mesh_announce
  become: true
  become_user: auto
  git: >
    repo=https://github.com/freifunkh/mesh-announce.git
    dest=/opt/mesh-announce
    accept_hostkey=true
  register: code

- name: Create configpath
  file:
    path: "{{ mesh_announce_cfg_path }}"
    state: directory

- name: Copy configuration file
  template:
    src: "respondd.conf.j2"
    dest: "{{ mesh_announce_cfg_path }}/respondd.conf"
  register: config

- name: Copy systemd service
  template:
    src: "respondd.service.j2"
    dest: "/lib/systemd/system/respondd.service"
  register: service

- name: Enable systemd service
  systemd:
    name: respondd
    enabled: yes
    daemon_reload: yes
    state: started
  when: (code.changed or config.changed or service.changed)