---

- hosts: "buildserver"
  pre_tasks:
    - name: "Import pre_tasks: reboot-required.yml"
      import_tasks: "include/reboot-required.yml"
      tags: [always]
    - name: "Import pre_task etckeeper"
      import_tasks: "include/etckeeper_pre.yml"
      tags: [always]
  roles:
    # General
    - { name: ff.networkd, tags: networkd, become: true }
    - { name: ff.certbot, tags: certbot, become: true }
    - { name: ff.firmware_selector, tags: firmware_selector, become: true }
    - { name: ff.buildserver, tags: buildserver, become: true }
  post_tasks:
    - name: "Import post_task etckeeper"
      import_tasks: "include/etckeeper_post.yml"
      tags: [always]
